apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-important
  namespace: project-01
  labels:
    id: very-important
spec:
  replicas: 3
  selector:
    matchLabels:
      id: very-important
  template:
    metadata:
      labels:
        id: very-important
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: id
                    operator: In
                    values:
                      - very-important
              topologyKey: kubernetes.io/hostname
      containers:
        - name: container1
          image: nginx:1-alpine
        - name: container2
          image: registry.k8s.io/pause:3.10
