apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-important
  namespace: project-02
  labels:
    id: very-important
spec:
  replicas: 3
  selector:
    matchLabels:
      id: very-important
  template:
    metadata:
      labels:
        id: very-important
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              id: very-important
      containers:
        - name: container1
          image: nginx:1-alpine
        - name: container2
          image: registry.k8s.io/pause:3.10
